### ISSUE TITLE
standalone-config.sql missing

### ISSUE THREAD

**Issue by misilot** [zemkat/grima#4]
The file standalone-config.sql is missing.

**Comment by zemkat** [comment]
To run grima locally, I now recommend the docker method instead of `standalone.sh`. A bug with docker.bat has now been fixed, so it should work better now. To use this option, download [docker.bat](../blob/master/docker/docker.bat) onto a Windows computer (with Docker installed) and edit that file to include your API key. Double-click `docker.bat`, and it should download the image and run automatically.

If you're using `standalone.sh`, the `standalone-config.sql` file stores your API key to Alma. It should be created automatically (an empty SQLite database) and then is populated on the first run of the grima website. The [setup documentation](../blob/master/docs/SETUP.md) has screenshots of this process. However, for a single user it is overly complicated, and standalone.sh should not be used for a large number of users. (I'll probably phase it out soon.)

**Comment by misilot** [comment]
Thank you that started right up. I did not realize there was a release and was using the code in master.
